webtalk_init -webtalk_dir C:\\Programiranje\\ProgramiMAS\\Projekt\\MAS_kamera\\camera\\camera.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-12-25 22:32:32" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "b11vm6qrcle6cd732c76665id4" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_20" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "20" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i5-4210U CPU @ 1.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.481 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1545699878102" -context "sdk\\\\bsp/1545699878102"
webtalk_add_data -client sdk -key hwid -value "1545163097468" -context "sdk\\\\bsp/1545699878102"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\bsp/1545699878102"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1545699878102"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1545699878102"
webtalk_add_data -client sdk -key uid -value "1545700173341" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key hwid -value "1545163097468" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key bspid -value "1545699878102" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key Procused -value "ps7_cortexa9" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key projSize -value "659.359375" -context "sdk\\\\application/1545700173341"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1545773552206"
webtalk_transmit -clientid 1416810518 -regid "" -xml C:\\Programiranje\\ProgramiMAS\\Projekt\\MAS_kamera\\camera\\camera.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html C:\\Programiranje\\ProgramiMAS\\Projekt\\MAS_kamera\\camera\\camera.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm C:\\Programiranje\\ProgramiMAS\\Projekt\\MAS_kamera\\camera\\camera.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
